name: calculator_plugin
description: Un package Flutter che fornisce un'interfaccia per operazioni matematiche di base.
version: 0.0.3
homepage: https://example.com
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
